wandb_version: 1

exp_name:
  desc: null
  value: 10-Oct-2023
gym_id:
  desc: null
  value: InvertedPendulum-v4
learning_rate:
  desc: null
  value: 0.00025
seed:
  desc: null
  value: 1
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: Prototype
wandb_entity:
  desc: null
  value: null
num_minibatches:
  desc: null
  value: 32
num_envs:
  desc: null
  value: 8
total_timesteps:
  desc: null
  value: 100000
num_steps:
  desc: null
  value: 800
update_epochs:
  desc: null
  value: 3
description:
  desc: null
  value: wandblogging
anneal_lr:
  desc: null
  value: true
batch_size:
  desc: null
  value: 6400
minibatch_size:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    code_path: code/cartpole/ppo/tparallel.py
    python_version: 3.9.16
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696922773.37462
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.16
      5: 0.15.11
      8:
      - 4
      - 5
      13: darwin-arm64
    visualize:
      Sampling Rollout time per step:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/line/v0
          fieldSettings:
            x: rollouts
            y: time per rollout
            stroke: null
          stringSettings:
            title: Sampling time per Step
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Sampling Rollout time per step_table
                fields: []
